#### activation  함수 이해

In [2]:
# import

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.python.framework import ops

In [3]:
# 그래프 초기화 및 세션 오픈
ops.reset_default_graph()
sess = tf.Session()

In [4]:
x_vals = np.linspace(start=-10., stop=10., num=100)
print(x_vals)

[-10.          -9.7979798   -9.5959596   -9.39393939  -9.19191919
  -8.98989899  -8.78787879  -8.58585859  -8.38383838  -8.18181818
  -7.97979798  -7.77777778  -7.57575758  -7.37373737  -7.17171717
  -6.96969697  -6.76767677  -6.56565657  -6.36363636  -6.16161616
  -5.95959596  -5.75757576  -5.55555556  -5.35353535  -5.15151515
  -4.94949495  -4.74747475  -4.54545455  -4.34343434  -4.14141414
  -3.93939394  -3.73737374  -3.53535354  -3.33333333  -3.13131313
  -2.92929293  -2.72727273  -2.52525253  -2.32323232  -2.12121212
  -1.91919192  -1.71717172  -1.51515152  -1.31313131  -1.11111111
  -0.90909091  -0.70707071  -0.50505051  -0.3030303   -0.1010101
   0.1010101    0.3030303    0.50505051   0.70707071   0.90909091
   1.11111111   1.31313131   1.51515152   1.71717172   1.91919192
   2.12121212   2.32323232   2.52525253   2.72727273   2.92929293
   3.13131313   3.33333333   3.53535354   3.73737374   3.93939394
   4.14141414   4.34343434   4.54545455   4.74747475   4.94949495
   5.151515

In [5]:
# 활성화 함수는 값의 범위를 제한 비선형 매핑
print(sess.run(tf.nn.relu([-3.,3.,10.])))

[-0.  3. 10.]


In [9]:
y_relu = sess.run(tf.nn.relu6(x_vals))

In [10]:
y_relu

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.1010101 , 0.3030303 , 0.50505051, 0.70707071, 0.90909091,
       1.11111111, 1.31313131, 1.51515152, 1.71717172, 1.91919192,
       2.12121212, 2.32323232, 2.52525253, 2.72727273, 2.92929293,
       3.13131313, 3.33333333, 3.53535354, 3.73737374, 3.93939394,
       4.14141414, 4.34343434, 4.54545455, 4.74747475, 4.94949

In [12]:
y_sigmoid = sess.run(tf.nn.sigmoid(x_vals))

In [13]:
y_tanh = sess.run(tf.nn.tanh(x_vals))

In [14]:
y_sigmoid

array([4.53978687e-05, 5.55606489e-05, 6.79983174e-05, 8.32200197e-05,
       1.01848815e-04, 1.24647146e-04, 1.52547986e-04, 1.86692945e-04,
       2.28478855e-04, 2.79614739e-04, 3.42191434e-04, 4.18766684e-04,
       5.12469082e-04, 6.27124987e-04, 7.67413430e-04, 9.39055039e-04,
       1.14904229e-03, 1.40591988e-03, 1.72012560e-03, 2.10440443e-03,
       2.57431039e-03, 3.14881358e-03, 3.85103236e-03, 4.70911357e-03,
       5.75728612e-03, 7.03711536e-03, 8.59898661e-03, 1.05038445e-02,
       1.28252101e-02, 1.56514861e-02, 1.90885420e-02, 2.32625358e-02,
       2.83228820e-02, 3.44451957e-02, 4.18339400e-02, 5.07243606e-02,
       6.13831074e-02, 7.41067363e-02, 8.92170603e-02, 1.07052146e-01,
       1.27951705e-01, 1.52235823e-01, 1.80176593e-01, 2.11963334e-01,
       2.47663801e-01, 2.87185901e-01, 3.30246430e-01, 3.76354517e-01,
       4.24816868e-01, 4.74768924e-01, 5.25231076e-01, 5.75183132e-01,
       6.23645483e-01, 6.69753570e-01, 7.12814099e-01, 7.52336199e-01,
      

In [18]:
# -1 값이 0.26으로 변환
sess.run(tf.nn.sigmoid([-1.,0.,1.]))

array([0.26894143, 0.5       , 0.7310586 ], dtype=float32)

In [15]:
y_tanh

array([-1.        , -0.99999999, -0.99999999, -0.99999999, -0.99999998,
       -0.99999997, -0.99999995, -0.99999993, -0.9999999 , -0.99999984,
       -0.99999977, -0.99999965, -0.99999947, -0.99999921, -0.99999882,
       -0.99999823, -0.99999735, -0.99999604, -0.99999406, -0.99999111,
       -0.99998668, -0.99998004, -0.99997011, -0.99995523, -0.99993294,
       -0.99989955, -0.99984955, -0.99977465, -0.99966248, -0.99949449,
       -0.9992429 , -0.99886619, -0.99830218, -0.99745797, -0.99619479,
       -0.9943057 , -0.99148279, -0.98726936, -0.98099146, -0.97166188,
       -0.95785067, -0.93752157, -0.90784899, -0.86506558, -0.8044548 ,
       -0.72069563, -0.60883666, -0.46607983, -0.2940833 , -0.10066796,
        0.10066796,  0.2940833 ,  0.46607983,  0.60883666,  0.72069563,
        0.8044548 ,  0.86506558,  0.90784899,  0.93752157,  0.95785067,
        0.97166188,  0.98099146,  0.98726936,  0.99148279,  0.9943057 ,
        0.99619479,  0.99745797,  0.99830218,  0.99886619,  0.99

In [19]:
# -1 값 포함
sess.run(tf.nn.tanh([-1.,0.,1.]))

array([-0.7615942,  0.       ,  0.7615942], dtype=float32)